### ISSUE TITLE
fints-cli does not work with winston 3.2.1

### ISSUE THREAD

**Issue by Icevarta** [Prior99/fints#8]
When trying to run fints-cli with winston 3.2.1 installed it fails because of this error:
```
TypeError: self._addDefaultMeta is not a function
    at Object.DerivedLogger.(anonymous function) [as verbose] (.../fints/node_modules/winston/lib/winston/create-logger.js:80:14)
    at HttpConnection.<anonymous> (.../fints/dist/http-connection.js:38:22)
    at Generator.next (<anonymous>)
    at .../fints/dist/http-connection.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (.../fints/dist/http-connection.js:3:12)
    at HttpConnection.send (.../fints/dist/http-connection.js:36:16)
    at Dialog.<anonymous> (.../fints/dist/dialog.js:132:52)
    at Generator.next (<anonymous>)
    at .../fints/dist/dialog.js:7:71
```
It seems this is a Problem in winston that will not get fixed:
[https://github.com/winstonjs/winston/issues/1591](https://github.com/winstonjs/winston/issues/1591)

**Comment by Prior99** [comment]
Do you jave any clue how to fix this?

**Comment by xaduha** [comment]
@Prior99 This is the only way I could make it run for me https://github.com/x-clone/fints

**Comment by gingerlime** [comment]
Getting the same problem. I just did a fresh install of fints-cll inside a docker node container (`npm install -g fints-cli`), and any command produces this error for me as well

```
TypeError: self._addDefaultMeta is not a function
    at Object.DerivedLogger.(anonymous function) [as verbose] (/usr/local/lib/node_modules/fints-cli/node_modules/winston/lib/winston/create-logger.js:80:14)
    at HttpConnection.<anonymous> (/usr/local/lib/node_modules/fints-cli/node_modules/fints/dist/http-connection.js:38:22)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/fints-cli/node_modules/fints/dist/http-connection.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/fints-cli/node_modules/fints/dist/http-connection.js:3:12)
    at HttpConnection.send (/usr/local/lib/node_modules/fints-cli/node_modules/fints/dist/http-connection.js:36:16)
    at Dialog.<anonymous> (/usr/local/lib/node_modules/fints-cli/node_modules/fints/dist/dialog.js:132:52)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/fints-cli/node_modules/fints/dist/dialog.js:7:71
```

**Comment by Prior99** [comment]
This package is using `yarn`, so `npm install` will lead to an incompatible version of winston to be installed. I also find it confusing how a minor upgrade of winston is breaking. I fixed this by changing the way the functions for logging are exported and publish the new versions.
